### ISSUE TITLE
Implement removal of song from room

### ISSUE THREAD

**Issue by wethegreenpeople** [wethegreenpeople/PartyPlaylists#3]
The room ID and song ID should both be passed via query string

**Comment by wethegreenpeople** [comment]
WebApi is deprecated now, implement behavior in either the RoomDataStore, or SongDataStore. Really feel free to implement this feature wherever it makes the most sense, within the PartyPlaylists class project.

**Comment by toastmalone** [comment]
I implemented this in the ToastMalone Branch in RoomSongDataStore.DeleteItemAsync. It only takes a string id as a parameter, I figured this was valid because a RoomSongs Id is a primary key.

**Comment by toastmalone** [comment]
Implemented and merged with master
